**Prérequis Python pour l'IA**

**Manipulation des données avec Numpy**

On doit importer la bibliothèque (module) numpy

In [5]:
import numpy as np

Les scalaires

In [45]:
 x=1
 y=2
 z=x+y
 z

3

Les vecteurs

In [47]:
x=np.array([1,2,3])
y=np.array([1,1,1])
z=x+y
z

array([2, 3, 4])

Les matrices

In [49]:
X=np.array([[1,2,3],[4,5,6]])
Y=np.array([[1,1,1],[2,2,2]])
Z=X+Y
Z

array([[2, 3, 4],
       [6, 7, 8]])

**Objet mathématique**

In [50]:
x=np.array([1,2,3])

In [51]:
x.dtype

dtype('int64')

In [52]:
x=np.array([1,2,3],dtype=np.uint8)

In [53]:
x

array([1, 2, 3], dtype=uint8)

In [54]:
x.dtype

dtype('uint8')

In [55]:
x+300

array([301, 302, 303], dtype=uint16)

In [56]:
x=np.array([1,2,300],dtype=np.uint8)

In [57]:
x

array([ 1,  2, 44], dtype=uint8)

In [58]:
x.ndim

1

In [59]:
x.shape

(3,)

In [60]:
type(x)

numpy.ndarray

In [62]:
x=np.array([1,2,3],dtype=np.uint8)

In [63]:
x.sum()

6

In [64]:
x.max()

3

In [65]:
x.argmax()

2

In [66]:
x[0]

1

In [67]:
x[-1]

3

In [68]:
x[:2]

array([1, 2], dtype=uint8)

In [69]:
x[::-1]

array([3, 2, 1], dtype=uint8)

In [70]:
len(x)

3

In [71]:
x.tolist()

[1, 2, 3]

In [72]:
L=[1,2,3]
x=np.array(L)

In [73]:
x

array([1, 2, 3])

In [74]:
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [75]:
np.sum(x)

6

In [76]:
x.sum()

6

In [77]:
x/2

array([0.5, 1. , 1.5])

In [78]:
x.sort()

In [79]:
x

array([1, 2, 3])

In [ ]:
x.sort()[::-1]

In [80]:
def somme(x,y):
  return x+y

def calcul(x,y,operation=somme):
  return operation(x,y)

In [81]:
calcul(1,2)

3

In [82]:
def produit(x,y):
  return x*y

def soustraction(x,y):
  return x-y

In [83]:
calcul(1,2,produit)

2

In [84]:
type(somme)

function

In [91]:
x=np.array([1,2,3],dtype=np.uint8)
np.sort(x)[::-1]

array([3, 2, 1], dtype=uint8)

**Exercice recap**

In [92]:
# Soient une population des employés caractérisée par leurs salaires et ages
# Soient deux employés Ali (salaire=1600 et age=38) et Sonia (salaire=2100 et age=43)
# Soit une requete (salaire=1500 et age=35)
# Quel est l'employé le plus proche à la requete ?

In [6]:
# representation mathematique des données
ali=np.array([1600,38])
sonia=np.array([2100,43])
requete=np.array([1500,35])

In [7]:
np.sqrt(np.dot(ali-sonia,ali-sonia)) # distance euclidienne entre Ali et Sonia (en 2D) 

500.02499937503126

In [8]:
# calcul/algorithme
# approche 1 : on définit la fonction de distance euclidienne
def distance(e1,e2):
  return np.sqrt(np.dot(e1-e2,e1-e2))

In [9]:
from numpy.linalg import norm   
norm(ali-sonia, ord=2)  

500.02499937503126

In [3]:
from scipy.spatial.distance import euclidean         
euclidean(ali,sonia)  

NameError: name 'ali' is not defined

In [11]:
d_req_ali=euclidean(requete,ali)
d_req_sonia=euclidean(requete,sonia)  
if d_req_ali<d_req_sonia:
  print('Ali est plus proche !')
elif d_req_ali>d_req_sonia:
  print('Sonia est plus proche !')
else:
  print('Les deux sont equidistants !')

NameError: name 'euclidean' is not defined

#what is panda ?    #panda is a library for data analysis in python      
#what is numpy ?    #numpy is a library for scientific computing in python
#what is IA ?       #IA is a branch of computer science that aims to create intelligent machines that work and react like humans
#what is DevOps ?   #DevOps is a set of practices that combines software development (Dev) and information technology operations (Ops)